openapi: 3.0.0
info:
  title: Tic Tac Toe API
  version: 1.0.0
  description: API for managing a Tic Tac Toe game. The board is a 3x3 grid with indices 0-8.

servers:
  - url: http://localhost:3000/api

paths:
  /resetBoard:
    get:
      summary: Reset the game board
      responses:
        '200':
          description: Board was reset
          content:
            text/plain:
              schema:
                type: string
                example: Board reset!

  /addMoveComputer:
    get:
      summary: Add a move by the computer
      responses:
        '200':
          description: Returns the result of the move.
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ---
                  -X-
                  ---

  /addMovePlayer:
    get:
      summary: Add a move by the next player
      parameters:
        - in: query
          name: x
          schema:
            type: integer
            minimum: 0
            maximum: 8
          required: true
          description: The index of the move attempted by the player
      responses:
        '200':
          description: Returns the result of the player's move.
          content:
            text/plain:
              schema:
                type: string
                example: |
                  ---
                  -X-
                  --O

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message describing what went wrong.
