name: CI Workflow

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify the Node.js version you need

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint  # Ensure your package.json has a lint script

      - name: Run Tests
        run: npm test  # Ensure your package.json has a test script
